CREATE TABLE LISTING_AI_SUMMARY (
    SUMMARY_ID BIGINT NOT NULL AUTO_INCREMENT,
    LISTING_ID BIGINT NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    PROMPT_VERSION VARCHAR(20) NOT NULL DEFAULT 'v1',
    SUMMARY_TEXT TEXT NOT NULL,
    HIGHLIGHTS TEXT NULL,
    CAUTIONS TEXT NULL,
    INPUT_HASH CHAR(64) NOT NULL,
    INPUT_TOKENS INT NULL,
    OUTPUT_TOKENS INT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    ERROR_MESSAGE VARCHAR(500) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SUMMARY_ID),
    UNIQUE KEY UX_AI_SUMMARY_LISTING (LISTING_ID),
    CONSTRAINT FK_AI_SUMMARY_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS (LISTING_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
