ALTER TABLE USERS
    ADD COLUMN NAME VARCHAR(50) NULL AFTER NICKNAME,
    ADD COLUMN BIRTH_DATE DATE NULL AFTER NAME,
    ADD COLUMN GENDER VARCHAR(10) NULL AFTER BIRTH_DATE;

CREATE INDEX IX_USERS_NAME_PHONE ON USERS (NAME, PHONE);
