ALTER TABLE REFUNDS
    ADD COLUMN USER_ID BIGINT NULL AFTER ORDER_ID,
    ADD COLUMN ADMIN_USER_ID BIGINT NULL AFTER STATUS,
    ADD COLUMN ADMIN_NOTE VARCHAR(500) NULL AFTER ADMIN_USER_ID,
    ADD COLUMN PG_CANCELLATION_ID VARCHAR(100) NULL AFTER COMPLETED_AT,
    ADD COLUMN PROCESSED_AT TIMESTAMP NULL AFTER PG_CANCELLATION_ID,
    ADD COLUMN UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER PROCESSED_AT;

UPDATE REFUNDS R
JOIN ORDERS O ON O.ORDER_ID = R.ORDER_ID
SET R.USER_ID = O.USER_ID
WHERE R.USER_ID IS NULL;

ALTER TABLE REFUNDS
    ADD KEY IX_REF_USER_STATUS (USER_ID, STATUS, REQUESTED_AT),
    ADD KEY IX_REF_STATUS (STATUS, REQUESTED_AT),
    ADD CONSTRAINT FK_REF_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    ADD CONSTRAINT FK_REF_ADMIN FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(USER_ID);
