ALTER TABLE LISTINGS
    ADD COLUMN BROKER_NAME VARCHAR(100) NULL AFTER SOURCE,
    ADD COLUMN BROKER_PHONE VARCHAR(30) NULL AFTER BROKER_NAME,
    ADD COLUMN BROKER_OFFICE_PHONE VARCHAR(30) NULL AFTER BROKER_PHONE,
    ADD COLUMN BROKER_OFFICE_NAME VARCHAR(150) NULL AFTER BROKER_OFFICE_PHONE;

UPDATE LISTINGS
SET BROKER_NAME = CONCAT('김', CASE MOD(LISTING_ID, 5)
        WHEN 0 THEN '민수'
        WHEN 1 THEN '지훈'
        WHEN 2 THEN '수연'
        WHEN 3 THEN '태민'
        ELSE '유진' END),
    BROKER_PHONE = CONCAT('010-',
        LPAD(1000 + MOD(LISTING_ID * 13, 9000), 4, '0'), '-',
        LPAD(1000 + MOD(LISTING_ID * 17, 9000), 4, '0')),
    BROKER_OFFICE_PHONE = CONCAT('02-',
        LPAD(100 + MOD(LISTING_ID * 3, 900), 3, '0'), '-',
        LPAD(1000 + MOD(LISTING_ID * 7, 9000), 4, '0')),
    BROKER_OFFICE_NAME = CONCAT(
        CASE MOD(LISTING_ID, 5)
            WHEN 0 THEN '디지털'
            WHEN 1 THEN '구로'
            WHEN 2 THEN '신도림'
            WHEN 3 THEN '가산'
            ELSE '프라임' END,
        ' 공인중개사사무소')
WHERE BROKER_NAME IS NULL;
