ALTER TABLE LISTINGS
    ADD COLUMN ROOM_COUNT TINYINT NOT NULL DEFAULT 1 COMMENT '방 개수' AFTER TOTAL_FLOOR,
    ADD COLUMN BATHROOM_COUNT TINYINT NOT NULL DEFAULT 1 COMMENT '화장실 개수' AFTER ROOM_COUNT;

ALTER TABLE PRODUCT_REVIEWS
    ADD COLUMN IMAGE_URL VARCHAR(500) NULL COMMENT '리뷰 이미지 URL' AFTER CONTENT;
