ALTER TABLE LISTINGS
    ADD COLUMN GU_CODE   VARCHAR(10) NULL COMMENT '구 코드' AFTER ADDRESS_DETAIL,
    ADD COLUMN GU_NAME   VARCHAR(50) NULL COMMENT '구 이름' AFTER GU_CODE,
    ADD COLUMN DONG_CODE VARCHAR(30) NULL COMMENT '동 코드' AFTER GU_NAME,
    ADD COLUMN DONG_NAME VARCHAR(50) NULL COMMENT '동 이름' AFTER DONG_CODE;

UPDATE LISTINGS
SET GU_NAME = SUBSTRING_INDEX(SUBSTRING_INDEX(ADDRESS_ROAD, ' ', 2), ' ', -1),
    DONG_NAME = SUBSTRING_INDEX(SUBSTRING_INDEX(ADDRESS_ROAD, ' ', 3), ' ', -1)
WHERE ADDRESS_ROAD LIKE '서울%'
  AND DELETED_AT IS NULL;

UPDATE LISTINGS
SET GU_CODE = GU_NAME,
    DONG_CODE = CONCAT(GU_NAME, '_', DONG_NAME)
WHERE GU_NAME IS NOT NULL
  AND DONG_NAME IS NOT NULL;

CREATE INDEX IX_LIST_REGION ON LISTINGS (GU_CODE, DONG_CODE);
