CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    PROFILE_IMAGE_URL VARCHAR(500) NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    OAUTH_PROVIDER VARCHAR(20) NULL,
    OAUTH_PROVIDER_ID VARCHAR(100) NULL,
    PHONE VARCHAR(20) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    LAST_LOGIN_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UX_USERS_EMAIL (EMAIL),
    UNIQUE KEY UX_USERS_OAUTH (OAUTH_PROVIDER, OAUTH_PROVIDER_ID),
    KEY IX_USERS_ROLE (ROLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USER_IDENTITY (
    IDENTITY_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    REAL_NAME VARCHAR(50) NOT NULL,
    RRN_ENCRYPTED VARBINARY(256) NOT NULL,
    RRN_HASH CHAR(64) NOT NULL,
    VERIFIED_AT TIMESTAMP NOT NULL,
    PORTONE_IMP_UID VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDENTITY_ID),
    UNIQUE KEY UX_IDENTITY_USER (USER_ID),
    CONSTRAINT FK_IDENTITY_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USER_ADDRESS (
    ADDRESS_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    LABEL VARCHAR(50) NOT NULL,
    RECEIVER_NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    ADDRESS_ROAD VARCHAR(255) NOT NULL,
    ADDRESS_DETAIL VARCHAR(255) NULL,
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ADDRESS_ID),
    KEY IX_ADDR_USER (USER_ID),
    CONSTRAINT FK_ADDR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
