CREATE TABLE OPTIONS (
    OPTION_ID SMALLINT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(30) NOT NULL,
    LABEL_KO VARCHAR(50) NOT NULL,
    ICON_NAME VARCHAR(50) NULL,
    PRIMARY KEY (OPTION_ID),
    UNIQUE KEY UX_OPTIONS_CODE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LISTINGS (
    LISTING_ID BIGINT NOT NULL AUTO_INCREMENT,
    HOST_USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION TEXT NULL,
    ROOM_TYPE VARCHAR(20) NOT NULL,
    DEAL_TYPE VARCHAR(20) NOT NULL,
    DEPOSIT INT NOT NULL,
    MONTHLY_RENT INT NOT NULL DEFAULT 0,
    MAINTENANCE_FEE INT NOT NULL DEFAULT 0,
    AREA_M2 DECIMAL(6,2) NOT NULL,
    FLOOR SMALLINT NULL,
    TOTAL_FLOOR SMALLINT NULL,
    ADDRESS_ROAD VARCHAR(255) NOT NULL,
    ADDRESS_DETAIL VARCHAR(255) NULL,
    LATITUDE DECIMAL(10,7) NOT NULL,
    LONGITUDE DECIMAL(10,7) NOT NULL,
    GEO_POINT POINT SRID 4326 NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    REJECT_REASON VARCHAR(500) NULL,
    SOURCE VARCHAR(20) NOT NULL DEFAULT 'HOST',
    VIEW_COUNT INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    PRIMARY KEY (LISTING_ID),
    KEY IX_LIST_STATUS (STATUS),
    KEY IX_LIST_HOST (HOST_USER_ID),
    KEY IX_LIST_DEAL (DEAL_TYPE, STATUS),
    KEY IX_LIST_PRICE (DEAL_TYPE, MONTHLY_RENT),
    SPATIAL KEY IX_LIST_GEO (GEO_POINT),
    CONSTRAINT FK_LIST_HOST FOREIGN KEY (HOST_USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LISTING_IMAGES (
    LISTING_IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT,
    LISTING_ID BIGINT NOT NULL,
    S3_URL VARCHAR(500) NOT NULL,
    SORT_ORDER SMALLINT NOT NULL DEFAULT 0,
    IS_COVER BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LISTING_IMAGE_ID),
    KEY IX_LIMG_LIST (LISTING_ID, SORT_ORDER),
    CONSTRAINT FK_LIMG_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LISTING_OPTIONS (
    LISTING_ID BIGINT NOT NULL,
    OPTION_ID SMALLINT NOT NULL,
    PRIMARY KEY (LISTING_ID, OPTION_ID),
    CONSTRAINT FK_LOPT_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LOPT_OPT FOREIGN KEY (OPTION_ID) REFERENCES OPTIONS(OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FAVORITES (
    USER_ID BIGINT NOT NULL,
    LISTING_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, LISTING_ID),
    KEY IX_FAV_USER (USER_ID, CREATED_AT DESC),
    CONSTRAINT FK_FAV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FAV_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LISTING_REPORTS (
    REPORT_ID BIGINT NOT NULL AUTO_INCREMENT,
    LISTING_ID BIGINT NOT NULL,
    REPORTER_USER_ID BIGINT NOT NULL,
    REASON VARCHAR(500) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPORT_ID),
    KEY IX_LREP_LIST (LISTING_ID, STATUS),
    CONSTRAINT FK_LREP_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID),
    CONSTRAINT FK_LREP_USER FOREIGN KEY (REPORTER_USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LISTING_AI_SUMMARY (
    LISTING_ID BIGINT NOT NULL,
    SUMMARY_TEXT VARCHAR(500) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    GENERATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LISTING_ID),
    CONSTRAINT FK_LAI_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
