CREATE TABLE PRODUCT_CATEGORIES (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
    PARENT_ID INT NULL,
    NAME VARCHAR(50) NOT NULL,
    DEPTH TINYINT NOT NULL,
    SORT_ORDER SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (CATEGORY_ID),
    KEY IX_PCAT_PARENT (PARENT_ID),
    CONSTRAINT FK_PCAT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODUCTS (
    PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    BRAND VARCHAR(100) NULL,
    PRICE INT NOT NULL,
    SALE_PRICE INT NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    WIDTH_CM SMALLINT NULL,
    DEPTH_CM SMALLINT NULL,
    HEIGHT_CM SMALLINT NULL,
    WEIGHT_KG DECIMAL(6,2) NULL,
    SHIPPING_FEE INT NOT NULL DEFAULT 0,
    DESCRIPTION_HTML MEDIUMTEXT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    PRIMARY KEY (PRODUCT_ID),
    KEY IX_PROD_CAT (CATEGORY_ID, STATUS),
    KEY IX_PROD_PRICE (SALE_PRICE),
    FULLTEXT KEY IX_PROD_NAME (NAME, BRAND),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODUCT_IMAGES (
    PRODUCT_IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    S3_URL VARCHAR(500) NOT NULL,
    SORT_ORDER SMALLINT NOT NULL DEFAULT 0,
    IS_COVER BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (PRODUCT_IMAGE_ID),
    KEY IX_PIMG_PROD (PRODUCT_ID, SORT_ORDER),
    CONSTRAINT FK_PIMG_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODUCT_OPTIONS (
    PRODUCT_OPTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    OPTION_TYPE VARCHAR(20) NOT NULL,
    OPTION_VALUE VARCHAR(100) NOT NULL,
    ADDITIONAL_PRICE INT NOT NULL DEFAULT 0,
    STOCK INT NOT NULL DEFAULT 0,
    PRIMARY KEY (PRODUCT_OPTION_ID),
    KEY IX_POPT_PROD (PRODUCT_ID),
    CONSTRAINT FK_POPT_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODUCT_REVIEWS (
    REVIEW_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ORDER_ITEM_ID BIGINT NOT NULL,
    RATING TINYINT NOT NULL,
    CONTENT TEXT NOT NULL,
    IMAGES JSON NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REVIEW_ID),
    UNIQUE KEY UX_REV_ORDER_ITEM (ORDER_ITEM_ID),
    KEY IX_REV_PROD (PRODUCT_ID, CREATED_AT DESC),
    CONSTRAINT FK_REV_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_REV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
