CREATE TABLE CARTS (
    CART_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CART_ID),
    UNIQUE KEY UX_CART_USER (USER_ID),
    CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CART_ITEMS (
    CART_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    CART_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_OPTION_ID BIGINT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    SOURCE_LISTING_ID BIGINT NULL,
    ADDED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CART_ITEM_ID),
    UNIQUE KEY UX_CART_ITEM (CART_ID, PRODUCT_ID, PRODUCT_OPTION_ID),
    KEY IX_CITEM_PROD (PRODUCT_ID),
    CONSTRAINT FK_CITEM_CART FOREIGN KEY (CART_ID) REFERENCES CARTS(CART_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CITEM_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_CITEM_POPT FOREIGN KEY (PRODUCT_OPTION_ID) REFERENCES PRODUCT_OPTIONS(PRODUCT_OPTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDERS (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ORDER_CODE VARCHAR(20) NOT NULL,
    ADDRESS_SNAPSHOT JSON NOT NULL,
    SUBTOTAL INT NOT NULL,
    SHIPPING_FEE INT NOT NULL DEFAULT 0,
    DISCOUNT INT NOT NULL DEFAULT 0,
    TOTAL INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    UNIQUE KEY UX_ORD_CODE (ORDER_CODE),
    KEY IX_ORD_USER_STATUS (USER_ID, STATUS, CREATED_AT DESC),
    CONSTRAINT FK_ORD_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_OPTION_ID BIGINT NULL,
    PRODUCT_SNAPSHOT JSON NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE INT NOT NULL,
    LINE_TOTAL INT NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    KEY IX_OITEM_ORD (ORDER_ID),
    CONSTRAINT FK_OITEM_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OITEM_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PAYMENTS (
    PAYMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    IMP_UID VARCHAR(100) NOT NULL,
    MERCHANT_UID VARCHAR(100) NOT NULL,
    METHOD VARCHAR(30) NOT NULL,
    AMOUNT INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PAID_AT TIMESTAMP NULL,
    RAW_RESPONSE JSON NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PAYMENT_ID),
    UNIQUE KEY UX_PAY_ORD (ORDER_ID),
    UNIQUE KEY UX_PAY_IMP (IMP_UID),
    CONSTRAINT FK_PAY_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE REFUNDS (
    REFUND_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    REASON VARCHAR(500) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    REQUESTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP NULL,
    PRIMARY KEY (REFUND_ID),
    KEY IX_REF_ORD (ORDER_ID, STATUS),
    CONSTRAINT FK_REF_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE COUPONS (
    COUPON_ID BIGINT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(30) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DISCOUNT_TYPE VARCHAR(10) NOT NULL,
    DISCOUNT_VALUE INT NOT NULL,
    MIN_ORDER_AMOUNT INT NOT NULL DEFAULT 0,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_TO TIMESTAMP NOT NULL,
    MAX_ISSUE INT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COUPON_ID),
    UNIQUE KEY UX_COUPON_CODE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USER_COUPONS (
    USER_COUPON_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    COUPON_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    ISSUED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USED_AT TIMESTAMP NULL,
    ORDER_ID BIGINT NULL,
    PRIMARY KEY (USER_COUPON_ID),
    KEY IX_UCOUP_USER (USER_ID, STATUS),
    CONSTRAINT FK_UCOUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_UCOUP_COUP FOREIGN KEY (COUPON_ID) REFERENCES COUPONS(COUPON_ID),
    CONSTRAINT FK_UCOUP_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
