CREATE TABLE CHAT_ROOMS (
    ROOM_ID BIGINT NOT NULL AUTO_INCREMENT,
    LISTING_ID BIGINT NOT NULL,
    GUEST_USER_ID BIGINT NOT NULL,
    HOST_USER_ID BIGINT NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP NULL,
    BLOCKED_BY_GUEST BOOLEAN NOT NULL DEFAULT FALSE,
    BLOCKED_BY_HOST BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROOM_ID),
    UNIQUE KEY UX_ROOM_LIST_GUEST (LISTING_ID, GUEST_USER_ID),
    KEY IX_ROOM_USER (GUEST_USER_ID, LAST_MESSAGE_AT DESC),
    KEY IX_ROOM_HOST (HOST_USER_ID, LAST_MESSAGE_AT DESC),
    CONSTRAINT FK_ROOM_LIST FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(LISTING_ID),
    CONSTRAINT FK_ROOM_GUEST FOREIGN KEY (GUEST_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_ROOM_HOST FOREIGN KEY (HOST_USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CHAT_MESSAGES (
    MESSAGE_ID BIGINT NOT NULL AUTO_INCREMENT,
    ROOM_ID BIGINT NOT NULL,
    SENDER_USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    CONTENT TEXT NULL,
    IMAGE_URL VARCHAR(500) NULL,
    VISIT_AT TIMESTAMP NULL,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MESSAGE_ID),
    KEY IX_MSG_ROOM (ROOM_ID, CREATED_AT),
    CONSTRAINT FK_MSG_ROOM FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOMS(ROOM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_SENDER FOREIGN KEY (SENDER_USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE NOTIFICATIONS (
    NOTI_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    BODY VARCHAR(500) NOT NULL,
    LINK_URL VARCHAR(500) NULL,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NOTI_ID),
    KEY IX_NOTI_USER (USER_ID, IS_READ, CREATED_AT DESC),
    CONSTRAINT FK_NOTI_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
