CREATE TABLE PUBLIC_REAL_ESTATE (
    DEAL_ID BIGINT NOT NULL AUTO_INCREMENT,
    REGION_CODE VARCHAR(10) NOT NULL,
    DEAL_TYPE VARCHAR(20) NOT NULL,
    AREA_M2 DECIMAL(6,2) NOT NULL,
    DEPOSIT INT NOT NULL,
    MONTHLY_RENT INT NOT NULL DEFAULT 0,
    DEAL_YEAR_MONTH CHAR(6) NOT NULL,
    BUILDING_NAME VARCHAR(200) NULL,
    FLOOR SMALLINT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEAL_ID),
    KEY IX_PRE_REGION_YM (REGION_CODE, DEAL_YEAR_MONTH),
    KEY IX_PRE_DEAL (DEAL_TYPE, DEAL_YEAR_MONTH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CRAWLED_LISTINGS (
    CRAWL_ID BIGINT NOT NULL AUTO_INCREMENT,
    SOURCE VARCHAR(50) NOT NULL,
    SOURCE_URL VARCHAR(500) NOT NULL,
    HASH CHAR(64) NOT NULL,
    RAW_JSON JSON NOT NULL,
    PROMOTED_LISTING_ID BIGINT NULL,
    CRAWLED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CRAWL_ID),
    UNIQUE KEY UX_CRAWL_URL (SOURCE_URL),
    UNIQUE KEY UX_CRAWL_HASH (HASH),
    KEY IX_CRAWL_PROMOTED (PROMOTED_LISTING_ID),
    CONSTRAINT FK_CRAWL_PROMOTED FOREIGN KEY (PROMOTED_LISTING_ID) REFERENCES LISTINGS(LISTING_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
