CREATE TABLE ADMIN_LOGS (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
    ADMIN_USER_ID BIGINT NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    TARGET_TYPE VARCHAR(50) NOT NULL,
    TARGET_ID BIGINT NULL,
    PAYLOAD JSON NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LOG_ID),
    KEY IX_ALOG_ADMIN (ADMIN_USER_ID, CREATED_AT DESC),
    KEY IX_ALOG_TARGET (TARGET_TYPE, TARGET_ID),
    CONSTRAINT FK_ALOG_ADMIN FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
