INSERT INTO OPTIONS (CODE, LABEL_KO, ICON_NAME) VALUES
('AIRCON', '에어컨', 'wind'),
('WASHER', '세탁기', 'washing-machine'),
('REFRIGERATOR', '냉장고', 'refrigerator'),
('MICROWAVE', '전자레인지', 'microwave'),
('GAS_STOVE', '가스레인지', 'flame'),
('INDUCTION', '인덕션', 'circle-dot'),
('BED', '침대', 'bed'),
('DESK', '책상', 'monitor'),
('WARDROBE', '옷장', 'archive'),
('SINK', '싱크대', 'sink'),
('TV', 'TV', 'tv'),
('INTERNET', '인터넷', 'wifi'),
('DOORLOCK', '도어락', 'lock'),
('CCTV', 'CCTV', 'video'),
('INTERPHONE', '인터폰', 'phone'),
('VIDEOPHONE', '비디오폰', 'phone-call'),
('PARKING', '주차', 'car'),
('ELEVATOR', '엘리베이터', 'arrow-up-down'),
('BALCONY', '베란다', 'square'),
('DRESSROOM', '드레스룸', 'shirt'),
('BATHTUB', '욕조', 'bath'),
('SHOE_RACK', '신발장', 'footprints'),
('BIDET', '비데', 'droplet'),
('PET_ALLOWED', '반려동물 가능', 'dog');
